Repository AndreasReitberger/LexOfficeClientSharp, pull requests merged in 2024-12, with the labels that each got.

#40 get documents
  src/LexOfficeSharpApi.Test.NUnit/UnitTest.cs
  src/LexOfficeSharpApi/LexOfficeClient.cs
Labels: enhancement, feature

#41 Merge `main` into branch
  src/LexOfficeSharpApi.Test.NUnit/UnitTest.cs
  src/LexOfficeSharpApi/LexOfficeClient.cs
Labels: enhancement

#43 Made `Clients` observable
  src/LexOfficeSharpApi/LexOfficeClient.cs
Labels: enhancement

#45 Added `RateLimitedHandler`
  src/LexOfficeSharpApi.Test.NUnit/UnitTest.cs
  src/LexOfficeSharpApi/LexOfficeClient.cs
  src/LexOfficeSharpApi/LexOfficeSharpApi.csproj
  src/LexOfficeSharpApi/Utilities/HeaderNames.cs
  src/LexOfficeSharpApi/Utilities/RateLimitedHandler.cs
Labels: enhancement, performance, feature
