Repository AndreasReitberger/LexOfficeClientSharp, pull requests merged in 2024-11, with the labels that each got.

#26 Create a new invoice
  src/LexOfficeSharpApi.Test.NUnit/UnitTest.cs
  src/LexOfficeSharpApi/Enum/LexContactType.cs
  src/LexOfficeSharpApi/Enum/LexVoucherStatus.cs
  src/LexOfficeSharpApi/Enum/LexVoucherType.cs
  src/LexOfficeSharpApi/LexOfficeClient.cs
  src/LexOfficeSharpApi/Model/Contact/LexContactAddress.cs
  src/LexOfficeSharpApi/Model/Invoice/LexCreateInvoice.cs
  src/LexOfficeSharpApi/Model/Invoice/LexInvoiceResponse.cs
  src/LexOfficeSharpApi/Model/Invoice/LexShippingConditions.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationItem.cs
Labels: enhancement, test

#27 Replaced `SecureString` with `String`
  src/LexOfficeSharpApi.Test.NUnit/UnitTest.cs
  src/LexOfficeSharpApi/LexOfficeClient.cs
  src/LexOfficeSharpApi/LexOfficeConnectionBuilder.cs
  src/LexOfficeSharpApi/Model/Invoice/LexCreateInvoice.cs
  src/LexOfficeSharpApi/Model/Invoice/LexShippingConditions.cs
Labels: enhancement, performance

#29 Updated dependencies
  art/ar_128.png
  common.props
  src/LexOfficeSharpApi.Test.NUnit/LexOfficeSharpApi.Test.NUnit.csproj
  src/LexOfficeSharpApi/LexOfficeSharpApi.csproj
Labels: enhancement, dependencies, nuget

#33 Added `UserSecrets` support
  src/LexOfficeSharpApi.Test.NUnit/LexOfficeSharpApi.Test.NUnit.csproj
  src/LexOfficeSharpApi.Test.NUnit/SecretAppSetting.cs
  src/LexOfficeSharpApi.Test.NUnit/SecretAppSettingReader.cs
  src/LexOfficeSharpApi.Test.NUnit/appSecretsExample.json
Labels: enhancement, test

#34 Added `GetPaymentConditionsAsync()`
  src/LexOfficeSharpApi.Test.NUnit/UnitTest.cs
  src/LexOfficeSharpApi/LexOfficeClient.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationDiscountCondition.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationItem.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationPaymentConditions.cs
Labels: enhancement

#36 Renamed `Enums` to start with a capital letter
  src/LexOfficeSharpApi.Test.NUnit/UnitTest.cs
  src/LexOfficeSharpApi/Enum/LexQuotationTaxType.cs
  src/LexOfficeSharpApi/Enum/LexVoucherStatus.cs
  src/LexOfficeSharpApi/Enum/LexVoucherType.cs
  src/LexOfficeSharpApi/LexOfficeClient.cs
  src/LexOfficeSharpApi/Model/Invoice/LexCreateInvoice.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationTaxConditions.cs
Labels: documentation, enhancement

#30 Get Payments
  src/LexOfficeSharpApi.Test.NUnit/UnitTest.cs
  src/LexOfficeSharpApi/LexOfficeClient.cs
  src/LexOfficeSharpApi/Model/Payment/LexPayment.cs
  src/LexOfficeSharpApi/Model/Payment/LexPayments.cs
Labels: enhancement, test
