Repository AndreasReitberger/LexOfficeClientSharp, pull requests merged in 2025-01, with the labels that each got.

#46 Add invoice correction
  src/LexOfficeSharpApi.Test.NUnit/UnitTest.cs
  src/LexOfficeSharpApi/LexOfficeClient.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationItem.cs
Labels: feature

#49 Add Event Subscription (Cleanup properties)
  src/LexOfficeSharpApi.Test.NUnit/UnitTest.cs
  src/LexOfficeSharpApi/LexOfficeClient.cs
  src/LexOfficeSharpApi/Model/Response/LexDocumentResponse.cs
  src/LexOfficeSharpApi/Model/Response/LexResponseDefault.cs
Labels: enhancement

#50 Show more details on Exception
  src/LexOfficeSharpApi/LexOfficeClient.cs
Labels: enhancement, feature

#52 Updated dependencies
  src/LexOfficeSharpApi/LexOfficeSharpApi.csproj
Labels: enhancement, dependencies, nuget

#53 Create dotnet_build_publish.yml
  .github/workflows/dotnet_build_publish.yml
Labels: enhancement, test

#54 Create dotnet_manual_housekeeping.yml
  .github/workflows/dotnet_manual_housekeeping.yml
Labels: enhancement

#57 Updated dependencies
  src/LexOfficeSharpApi.Test.NUnit/LexOfficeSharpApi.Test.NUnit.csproj
Labels: dependencies, nuget, t/housekeeping ♻︎

#59 Fixed warnings
  src/LexOfficeSharpApi/LexOfficeClient.cs
  src/LexOfficeSharpApi/Model/Response/LexResponseDefault.cs
  src/LexOfficeSharpApi/Model/Response/LexResponseWrapper.cs
Labels: t/housekeeping ♻︎

#60 Switched to `RestApiClient`
  common.props
  src/LexOfficeSharpApi.Test.NUnit/LexOfficeSharpApi.Test.NUnit.csproj
  src/LexOfficeSharpApi.Test.NUnit/UnitTest.cs
  src/LexOfficeSharpApi/LexOfficeClient.Conditions.cs
  src/LexOfficeSharpApi/LexOfficeClient.Contacts.cs
  src/LexOfficeSharpApi/LexOfficeClient.Countries.cs
  src/LexOfficeSharpApi/LexOfficeClient.CreditNotes.cs
  src/LexOfficeSharpApi/LexOfficeClient.Documents.cs
  src/LexOfficeSharpApi/LexOfficeClient.ErrorHandling.cs
  src/LexOfficeSharpApi/LexOfficeClient.Invoices.cs
  src/LexOfficeSharpApi/LexOfficeClient.NetFramework.cs
  src/LexOfficeSharpApi/LexOfficeClient.Payments.cs
  src/LexOfficeSharpApi/LexOfficeClient.Proxy.cs
  src/LexOfficeSharpApi/LexOfficeClient.Quotations.cs
  src/LexOfficeSharpApi/LexOfficeClient.Subscriptions.cs
  src/LexOfficeSharpApi/LexOfficeClient.cs
  src/LexOfficeSharpApi/LexOfficeConnectionBuilder.cs
  src/LexOfficeSharpApi/LexOfficeSharpApi.csproj
  src/LexOfficeSharpApi/Model/Contact/LexContact.cs
  src/LexOfficeSharpApi/Model/Contact/LexContactAddress.cs
  src/LexOfficeSharpApi/Model/Contact/LexContactCompany.cs
  src/LexOfficeSharpApi/Model/Contact/LexContactPerson.cs
  src/LexOfficeSharpApi/Model/Contact/LexContactsList.cs
  src/LexOfficeSharpApi/Model/Country/LexCountry.cs
  src/LexOfficeSharpApi/Model/Customer/LexCustomerNumber.cs
  src/LexOfficeSharpApi/Model/Invoice/LexCreateInvoice.cs
  src/LexOfficeSharpApi/Model/Invoice/LexInvoiceResponse.cs
  src/LexOfficeSharpApi/Model/Invoice/LexShippingConditions.cs
  src/LexOfficeSharpApi/Model/Payment/LexPayment.cs
  src/LexOfficeSharpApi/Model/Payment/LexPayments.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotation.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationDiscountCondition.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationFiles.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationItem.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationPaymentConditions.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationTaxAmount.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationTaxConditions.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationTotalPrice.cs
  src/LexOfficeSharpApi/Model/Quotation/LexQuotationUnitPrice.cs
  src/LexOfficeSharpApi/Model/Response/LexDocumentResponse.cs
  src/LexOfficeSharpApi/Model/Response/LexResponseDefault.cs
  src/LexOfficeSharpApi/Model/Voucher/LexVoucherList.cs
  src/LexOfficeSharpApi/Model/Voucher/LexVoucherSort.cs
  src/LexOfficeSharpApi/Model/Voucher/VoucherListContent.cs
  src/LexOfficeSharpApi/Struct/AcceptedFileHeaders.cs
Labels: enhancement, dependencies, feature, t/housekeeping ♻︎
